name: Node.js Testing CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Test-NodeJS-Linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.18]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node Modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-linux-${{ hashFiles('package-lock.json') }}

      - name: Install Node dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run Node tests
        run: npm test
